apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: harperdb
  namespace: harperdb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: harperdb
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: harperdb
    spec:
      containers:
        - name: harperdb
          image: harperdb/harperdb
          env:
            - name: CLUSTERING_NODENAME
              value: { { randAlphaNum 5 } }
          envFrom:
            - secretRef:
                name: harperdb
