# https://numtide.github.io/devshell
[[commands]]
package = "devshell.cli"
help = "Per project developer environments"

[[commands]]
package = "terraform"
name = "tf"

[[commands]]
package = "emacs"

[[commands]]
package = "kubectl"
name = "k"

[[commands]]
package = "linkerd"

[[env]]
name = "KUBECONFIG"
value = "./.temp/kubeconfig"
