# https://numtide.github.io/devshell
[[commands]]
package = "devshell.cli"
help = "Per project developer environments"

[[commands]]
package = "terraform"
help = "yep"
name = "tf"

[[commands]]
package = "emacs"
help = "Editor"
